/**
 * Copyright (c) 2011-2026 libbitcoin-system developers (see AUTHORS)
 *
 * This file is part of libbitcoin.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef LIBBITCOIN_SYSTEM_UNICODE_UNICODE_TABLES_HPP
#define LIBBITCOIN_SYSTEM_UNICODE_UNICODE_TABLES_HPP

#include <cstddef>
#include <cstdint>

// Generated by tools/generate_unicode_tables.py
// Unicode version: 15.0.0

namespace libbitcoin {
namespace system {

constexpr size_t decomposition_pool_count = 10320;
constexpr size_t decomposition_index1_count = 8704;
constexpr size_t decomposition_index2_count = 13568;
constexpr size_t composition_pairs_count = 941;
constexpr size_t case_fold_pairs_count = 1530;
constexpr size_t upper_pairs_count = 1423;

extern const uint32_t decomposition_pool[decomposition_pool_count];
extern const uint16_t decomposition_index1[decomposition_index1_count];
extern const uint16_t decomposition_index2[decomposition_index2_count];
extern const uint32_t composition_pairs[composition_pairs_count * 3];
extern const uint32_t case_fold_pairs[case_fold_pairs_count * 5];
extern const uint32_t upper_pairs[upper_pairs_count * 5];

} // namespace system
} // namespace libbitcoin

#endif
