#!/usr/bin/env python3
"""
Generate the embedded cuda kernels (ptx) for libbitcoin-system.

Source: src/crypto/secp256k1/cuda/verify.cu, compiled for the device by clang
        (no cuda toolkit), then raw deflated for embedding.
Output: src/crypto/secp256k1/cuda/ptx.cpp

Run from the repository root, after a build has generated version.hpp:
  python3 tools/generate_cuda_ptx.py --boost <boost-include-directory>

On Windows the Visual Studio clang is used (C++ Clang Compiler component),
otherwise clang++ on the path, or the --clang argument.
"""

import argparse
import os
import subprocess
import sys
import tempfile
import zlib

SOURCE = os.path.join("src", "crypto", "secp256k1", "cuda", "verify.cu")
OUTPUT = os.path.join("src", "crypto", "secp256k1", "cuda", "ptx.cpp")
ARCHITECTURE = "sm_75"

LICENSE_HEADER = """\
/**
 * Copyright (c) 2011-2026 libbitcoin developers
 *
 * This file is part of libbitcoin.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
"""

# ── compile ─────────────────────────────────────────────────────────────────

def visual_studio():
    """Installation path of the latest Visual Studio, or None."""
    vswhere = os.path.join(os.environ.get("ProgramFiles(x86)", ""),
        "Microsoft Visual Studio", "Installer", "vswhere.exe")
    if not os.path.exists(vswhere):
        return None
    path = subprocess.run([vswhere, "-latest", "-property",
        "installationPath"], capture_output=True, text=True).stdout.strip()
    return path or None


def compile_ptx(clang, boost, ptx):
    """Compile the kernels for the device, writing ptx text."""
    arguments = [
        "-x", "cuda", "--cuda-device-only",
        "--cuda-gpu-arch=" + ARCHITECTURE,
        "-nocudainc", "-nocudalib", "-std=c++20", "-O3", "-S",
        "-D__host__=__attribute__((host))",
        "-D__device__=__attribute__((device))",
        "-D__global__=__attribute__((global))",
        "-DENABLE_PTX", "-DNDEBUG", "-DBOOST_ALL_NO_LIB", "-DBOOST_URL_HPP",
        "-I", "include", "-I", os.path.join("build", "include"),
        "-I", boost, SOURCE, "-o", ptx]

    if os.name == "nt":
        install = visual_studio()
        if install is None:
            sys.exit("Visual Studio not found.")
        vcvars = os.path.join(install, "VC", "Auxiliary", "Build",
            "vcvars64.bat")
        if clang is None:
            clang = os.path.join(install, "VC", "Tools", "Llvm", "x64",
                "bin", "clang++.exe")
        arguments.insert(0, "-D_WIN32_WINNT=0x0A00")
        command = 'call "{}" >nul && "{}" {}'.format(vcvars, clang,
            subprocess.list2cmdline(arguments))
        result = subprocess.run('cmd /s /c "{}"'.format(command))
    else:
        result = subprocess.run([clang or "clang++"] + arguments)

    if result.returncode != 0:
        sys.exit("ptx compilation failed.")


# ── emit ────────────────────────────────────────────────────────────────────

def deflate(data):
    """Raw deflate (no zlib header), as inflated by beast::zlib."""
    compressor = zlib.compressobj(level=9, method=zlib.DEFLATED, wbits=-15,
        memLevel=8, strategy=zlib.Z_DEFAULT_STRATEGY)
    return compressor.compress(data) + compressor.flush()


def generate_cpp(deflated, size):
    """The embedding source, compiled only where cuda is enabled."""
    lines = [LICENSE_HEADER.rstrip("\n"),
        '#include "ptx.hpp"',
        "",
        "#include <bitcoin/system/data/data.hpp>",
        "#include <bitcoin/system/define.hpp>",
        "",
        "// Generated by tools/generate_cuda_ptx.py from verify.cu.",
        "",
        "#if defined(HAVE_CUDA)",
        "",
        "namespace libbitcoin {",
        "namespace system {",
        "namespace secp256k1 {",
        "namespace cuda {",
        "",
        "constexpr std_array<uint8_t, {}> deflated".format(len(deflated)),
        "{"]

    columns = 12
    for row in range(0, len(deflated), columns):
        part = deflated[row:row + columns]
        text = ", ".join("0x{:02x}".format(byte) for byte in part)
        last = row + columns >= len(deflated)
        lines.append("    " + text + ("" if last else ","))

    lines += ["};",
        "",
        "data_slice deflated_ptx() NOEXCEPT",
        "{",
        "    return deflated;",
        "}",
        "",
        "size_t ptx_size() NOEXCEPT",
        "{",
        "    return {};".format(size),
        "}",
        "",
        "} // namespace cuda",
        "} // namespace secp256k1",
        "} // namespace system",
        "} // namespace libbitcoin",
        "",
        "#endif",
        ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument("--boost", required=True,
        help="boost include directory")
    parser.add_argument("--clang", help="clang++ executable")
    options = parser.parse_args()

    if not os.path.exists(SOURCE):
        sys.exit("Run from the repository root.")

    with tempfile.TemporaryDirectory() as directory:
        ptx = os.path.join(directory, "verify.ptx")
        compile_ptx(options.clang, options.boost, ptx)
        with open(ptx, "rb") as file:
            data = file.read()

    deflated = deflate(data)
    with open(OUTPUT, "w", newline="\n") as file:
        file.write(generate_cpp(deflated, len(data)))

    print("ptx {} bytes, deflated {} bytes, wrote {}".format(len(data),
        len(deflated), OUTPUT))


if __name__ == "__main__":
    main()
